spring:
    datasource:
        url: jdbc:h2:mem:hogwarts
        username: sa
        password: 
        driver-class-name: org.h2.Driver
    jpa:
        show-sql: true
    security:
        user:
            name: admin
            password: 1234
            roles: USER
logging:
    level:
        com.valik.hogwarts_artifacts_online.security: DEBUG
api:
    endpoint:
        base-url: /api/v1
